version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - mvn clean package
  post_build:
    commands:
      - echo Build successful
artifacts:
  files:
    - target*/*
  discard-paths: yes
  
cache:
  paths:
    - '/root/.m2/**/*'
  